version: "3"

services:
  nail_studio:
    image: zhivkotringov/nail-studio:2024_02
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind=0.0.0.0 Nail_studio.wsgi:application
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /tmp/app-resources/static:/app/static
    networks:
      - nail_studio
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nail_studio_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - nail_studio


  pgadmin4:
    image: dpage/pgadmin4
    user: "${UID}:${GID}" # to avoid permission issues
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin4:/var/lib/pgadmin
    ports:
      - "5433:5433"
    depends_on:
      - postgres
    networks:
      - nail_studio

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/nail_studio/static:home/app/nail-studio/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - nail_studio

networks:
  nail_studio:
    driver: bridge