# Generated by Django 4.2.3 on 2023-07-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_services_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
