# Generated by Django 4.2.3 on 2023-08-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_appuser_is_manicurist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
