# Generated by Django 4.2.3 on 2023-08-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0007_alter_appuser_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='first_name',
        ),
    ]
