# Generated by Django 4.2.3 on 2023-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
