# Generated by Django 4.2.3 on 2023-07-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_services_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'permissions': [('manage_services', 'Can manage services')]},
        ),
    ]
