# Generated by Django 4.2.3 on 2023-08-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryphoto_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryphoto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
