# Generated by Django 4.2.3 on 2023-07-29 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_manicurist_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_ordered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
