# Generated by Django 4.2.3 on 2023-07-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_appuser_is_manicurist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_alter_appointment_time_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manicurist',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'is_manicurist': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.manicurist'),
        ),
    ]
