# Generated by Django 4.2.3 on 2023-07-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_manicurist_appointment_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manicurist',
            old_name='user',
            new_name='UserModel',
        ),
    ]
