# Generated by Django 4.2.3 on 2023-07-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_rename_user_manicurist_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manicurist',
            old_name='UserModel',
            new_name='manicurist',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(limit_choices_to={'is_manicurist': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.manicurist'),
        ),
    ]
