# Generated by Django 4.2.3 on 2023-07-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_manicurist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.manicurist'),
        ),
    ]
