# Generated by Django 4.2.3 on 2023-07-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_alter_appointment_manicurist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_first_name',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
    ]
