# Generated by Django 4.2.3 on 2023-07-29 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0002_appuser_is_manicurist'),
        ('appointments', '0012_remove_appointment_manicurist_appointment_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manicurist',
            fields=[
                ('manicurist', models.OneToOneField(limit_choices_to={'is_manicurist': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.manicurist'),
        ),
    ]
