# Generated by Django 4.2.3 on 2023-07-29 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0013_manicurist_appointment_manicurist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manicurist',
            name='manicurist',
        ),
        migrations.AddField(
            model_name='manicurist',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'is_manicurist': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manicurist_profile', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manicurist_appointments', to='appointments.manicurist'),
        ),
    ]
