# Generated by Django 4.2.3 on 2023-07-29 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0014_remove_manicurist_manicurist_manicurist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_first_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(limit_choices_to={'is_manicurist': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Manicurist',
        ),
    ]
