# Generated by Django 4.2.3 on 2023-07-29 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0015_remove_appointment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_by',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='manicurist',
            field=models.ForeignKey(limit_choices_to={'is_manicurist': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
