# Generated by Django 4.2.3 on 2023-08-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_appointment_end_time_appointment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
