# Generated by Django 4.2.3 on 2023-08-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_alter_appointment_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
