# Generated by Django 4.2.3 on 2023-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_remove_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
    ]
