# Generated by Django 4.2.3 on 2023-08-05 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_remove_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('10:30', '10:30'), ('11:30', '11:30'), ('12:30', '12:30'), ('13:30', '13:30'), ('14:30', '14:30'), ('15:30', '15:30'), ('16:30', '16:30'), ('17:30', '17:30'), ('18:30', '18:30')], default='10:30', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booked_by',
            field=models.CharField(blank=True, default=None, editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
