# Generated by Django 4.2.3 on 2023-08-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_appointment_day_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
