# Generated by Django 4.2.3 on 2023-08-06 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0022_remove_appointment_day_remove_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('manicurist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
