# Generated by Django 4.2.3 on 2023-08-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_availableappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AvailableAppointment',
        ),
    ]
