# Generated by Django 4.2.3 on 2023-08-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='date',
        ),
    ]
