# Generated by Django 4.2.3 on 2023-08-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_availabletimeslot_remove_appointment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableTimeSlot',
        ),
    ]
