# Generated by Django 4.2.3 on 2023-07-26 15:56

import Nail_studio.services.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('Нокти', 'Нокти'), ('Мигли', 'Мигли'), ('Кола маска', 'Кола маска'), ('Лице', 'Лице'), ('Други', 'Други')], default='Нокти', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxValueValidator(50), Nail_studio.services.models.validate_isalpha]),
        ),
    ]
