# Generated by Django 4.2.3 on 2023-07-26 15:59

import Nail_studio.services.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_categories_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(50), Nail_studio.services.models.validate_isalpha]),
        ),
    ]
