# Generated by Django 4.2.3 on 2023-07-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='categories',
            field=models.CharField(choices=[('Нокти', 'Нокти'), ('Вежди', 'Вежди'), ('Кола маска', 'Кола маска'), ('Лице', 'Лице'), ('Други', 'Други')], default='Нокти', max_length=50),
        ),
    ]
