# Generated by Django 4.2.3 on 2023-08-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in minutes'),
            preserve_default=False,
        ),
    ]
