name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker-compose build
      - name: Run Django tests
        run: docker-compose run nail_studio python manage.py test
