name: Nail_studio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  docker:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            nail_studio
            postgres
          build: true  # Add this if you need to build images
      - name: Set up environment variables
        run: |
          echo "POSTGRES_USER=postgres" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=postgres" >> $GITHUB_ENV
          echo "POSTGRES_DB=postgres" >> $GITHUB_ENV
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "SECRET_KEY=super secret" >> $GITHUB_ENV
      - name: Run tests
        run: |
          docker exec nail_studio_project-nail_studio-1 python manage.py test
